# Generated by Django 5.0.6 on 2024-06-23 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corretora",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome_corretora", models.CharField(max_length=255, verbose_name="Nome Corretora")),
                ("telefone", models.CharField(max_length=12, verbose_name="Telefone")),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True, verbose_name="Email")),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name="CNPJ")),
                ("pessoa_contato", models.CharField(max_length=100, verbose_name="Contato")),
                ("concordo", models.BooleanField(verbose_name="Concordo")),
            ],
            options={
                "verbose_name": "Corretora",
                "verbose_name_plural": "Corretoras",
            },
        ),
    ]
