# Generated by Django 5.0.6 on 2024-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_corretora_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corretora",
            name="cnpj",
            field=models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name="CNPJ"),
        ),
    ]
