# Generated by Django 5.0.6 on 2024-06-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_corretora_concordo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corretora",
            name="concordo",
        ),
    ]
